// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCijO24OK7KYbRDbEuejdK91nxjBYMKTs0',
    appId: '1:152959071951:web:86f00a8da4db8743b429ba',
    messagingSenderId: '152959071951',
    projectId: 'flutter2-793f1',
    authDomain: 'flutter2-793f1.firebaseapp.com',
    storageBucket: 'flutter2-793f1.appspot.com',
    measurementId: 'G-6KS2TTL4HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAryAtQfwhkoVG0XRBGIL_nRGZmV_KiAsY',
    appId: '1:152959071951:android:9229d733f6d1b696b429ba',
    messagingSenderId: '152959071951',
    projectId: 'flutter2-793f1',
    storageBucket: 'flutter2-793f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKWBJzRhK338zgZk2g3YZQ-KbU74ipAhE',
    appId: '1:152959071951:ios:1f095321edac6c2fb429ba',
    messagingSenderId: '152959071951',
    projectId: 'flutter2-793f1',
    storageBucket: 'flutter2-793f1.appspot.com',
    iosBundleId: 'com.example.abc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKWBJzRhK338zgZk2g3YZQ-KbU74ipAhE',
    appId: '1:152959071951:ios:d8218299882f9dbfb429ba',
    messagingSenderId: '152959071951',
    projectId: 'flutter2-793f1',
    storageBucket: 'flutter2-793f1.appspot.com',
    iosBundleId: 'com.example.abc.RunnerTests',
  );
}
